version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@nuxtjs/dayjs"
    versions:
    - 1.3.0
    - 1.3.1
  - dependency-name: "@nuxtjs/tailwindcss"
    versions:
    - 3.4.2
    - 3.4.3
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
